apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-helm-chart
spec:
  destination:
    namespace: nginx
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/HIRO-MicroDataCenters-BV/argocd-demo.git
    path: hello-world-chart/hello-world
    targetRevision: main
  helm:
    valueFiles:
      - values.yaml
